### PR TITLE
Adjust module to new engine version

### PR DESCRIPTION
**Pull request by ottiker**
Adjust module to new engine version

### CODE REVIEW

**Comment by IonicaBizau** [comment]
I guess docs need to be updated, right?

**Comment by gabipetrovay** [comment]
Yes, still things have to be checked before this can be merged. And of course documentation.

**Comment by gabipetrovay** [comment]
@adioo @IonicaBizau Anyone wants to merge this?

**Comment by ottiker** [comment]
@gabipetrovay I'm gonna merge it.

**Comment by ottiker** [comment]
There's a [no-streams](https://github.com/adioo/view/releases/tag/no-streams) tag, which is compatible with the "old" engine version.

**Pull request merged**
